apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-storage-ocs
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  
