{
 "title": "Custom Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "http_server_requests_seconds_max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/metrics\",}"
    }
   ]
  },
  {
   "title": "Project  Cpu usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(topk(25, sort_desc(sum(avg_over_time(pod:container_cpu_usage:sum{container=\"\",pod!=\"\",namespace='ns1'}[1m])) BY (pod, namespace))))*1000",
     "legendFormat": "CPU Millicore"
    }
   ]
  },
  {
   "title": "Pod replicas count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"ns1\"}) by (namespace)",
     "legendFormat": "Pod Replicas"
    }
   ]
  },
  {
   "title": "Version (Custom metric)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "version{namespace=\"ns1\"}"
    }
   ]
  },
  {
   "title": "Project NS1 - http_requests_total_per_minute (Custom metric)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"ns1\"}[1m]))\n"
    }
   ]
  },
  {
   "title": "Project Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(topk(25, sort_desc(sum(avg_over_time(container_memory_working_set_bytes{container=\"\",pod!=\"\",namespace='ns1'}[5m])) BY (pod, namespace))))"
    }
   ]
  }
 ]
}