apiVersion: v1
items:
- apiVersion: integreatly.org/v1alpha1
  kind: Grafana
  metadata:
    creationTimestamp: "2021-04-28T13:12:50Z"
    generation: 7
    name: example-grafana
    namespace: grafana2
    resourceVersion: "3584817"
    selfLink: /apis/integreatly.org/v1alpha1/namespaces/grafana2/grafanas/example-grafana
    uid: 86095d2e-38e0-44e8-b108-05e526e1decd
  spec:
    config:
      auth:
        disable_signout_menu: true
      auth.anonymous:
        enabled: true
      log:
        level: warn
        mode: console
      security:
        admin_password: secret
        admin_user: root
    configMaps:
    - ocp-injected-certs
    containers:
    - args:
      - -provider=openshift
      - -pass-basic-auth=false
      - -https-address=:9091
      - -http-address=
      - -email-domain=*
      - -upstream=http://localhost:3000
      - -tls-cert=/etc/tls/private/tls.crt
      - -tls-key=/etc/tls/private/tls.key
      - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
      - -cookie-secret-file=/etc/proxy/secrets/session_secret
      - -openshift-service-account=grafana-serviceaccount
      - -openshift-ca=/etc/pki/tls/cert.pem
      - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      - -openshift-ca=/etc/grafana-configmaps/ocp-injected-certs/ca-bundle.crt
      - -skip-auth-regex=^/metrics
      - '-openshift-sar={"namespace": "grafana2", "resource": "services","verb": "get"}'
      image: quay.io/openshift/origin-oauth-proxy:4.6
      name: grafana-proxy
      ports:
      - containerPort: 9091
        name: grafana-proxy
      resources: {}
      volumeMounts:
      - mountPath: /etc/tls/private
        name: secret-grafana-k8s-tls
        readOnly: false
      - mountPath: /etc/proxy/secrets
        name: secret-grafana-k8s-proxy
        readOnly: false
    dashboardLabelSelector:
    - matchExpressions:
      - key: app
        operator: In
        values:
        - grafana
    ingress:
      enabled: true
      targetPort: grafana-proxy
      termination: reencrypt
    secrets:
    - grafana-k8s-tls
    - grafana-k8s-proxy
    service:
      annotations:
        service.alpha.openshift.io/serving-cert-secret-name: grafana-k8s-tls
      ports:
      - name: grafana-proxy
        port: 9091
        protocol: TCP
        targetPort: grafana-proxy
    serviceAccount:
      annotations:
        serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}'
  status:
    dashboards: null
    failedPlugins: null
    installedPlugins: null
    message: success
    phase: reconciling
    previousServiceName: grafana-service
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
