apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: "2023-02-09T00:05:49Z"
  generation: 1
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
    prometheus: k8s
    role: alert-rules
  name: cluster-monitoring-operator-prometheus-rules-pietro-etcd2
  namespace: default
spec:
  groups:
  - name: openshift-general.rules
    rules:
    - alert: etcdHighFsyncDurationsSuperPietro
      annotations:
        description: 'etcd cluster "{{ $labels.job }}": 99th percentile fsync durations
          are {{ $value }}s on etcd instance {{ $labels.instance }}.'
        summary: etcd cluster 99th percentile fsync durations are too high.
      expr: |
        histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~".*etcd.*"}[5m]))
        > 0.001
      for: 5m
      labels:
        severity: warning


'{"spec":{"tlsSecurityProfile":{"type":"Intermediate","intermediate":{}}}}'





oc patch ingresscontrollers.operator.openshift.io default  -n openshift-ingress-operator -p '{"spec":{"tlsSecurityProfile":{"type":"Intermediate","intermediate":{}}}}' --type merge





























































































































































































































































