apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: valez_provider
    type: HTPasswd
  - ldap:
      attributes:
        email:
        - mail
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: uid=admin,cn=users,cn=accounts,dc=lab,dc=seeweb
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: ldaps://idm.lab.seeweb/cn=users,cn=accounts,dc=lab,dc=seeweb?uid?sub?(memberof=cn=ocp,cn=groups,cn=accounts,dc=lab,dc=seeweb)
    mappingMethod: claim
    name: ldapidp
    type: LDAP
