apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-credentials
type: Opaque
data:
  username: VmFsZW50aW5vVWJlcnRpCg== 
  password: MTFDYXNhZnUxMQo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-repo-config
data:
  repositories: |
    - url: https://github.com/ValentinoUberti/test.git
      passwordSecret:
        name: argocd-repo-credentials
        key: password
      usernameSecret:
        name: argocd-repo-credentials
        key: username


