apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: logging.openshift.io/v1
  kind: ClusterLogging
  metadata:
    name: instance
    namespace: openshift-logging
  spec:
    collection:
      logs:
        fluentd: {}
        type: fluentd
    curation:
      curator:
        schedule: 30 3 * * *
        nodeSelector: 
          node-role.kubernetes.io/infra: ''
        tolerations:
        - effect: NoSchedule 
          key: node-role.kubernetes.io/infra 
          operator: Exists
          
      type: curator
    logStore:
      elasticsearch:
        nodeCount: 3
        redundancyPolicy: SingleRedundancy
        nodeSelector: 
          node-role.kubernetes.io/infra: ''
        tolerations:
        - effect: NoSchedule 
          key: node-role.kubernetes.io/infra 
          operator: Exists
         
        storage:
          size: 200G
          storageClassName: managed-premium
        resources:
          limits:
            cpu: 500m
            memory: 16Gi
          requests:
            cpu: 500m
            memory: 16Gi
      retentionPolicy:
        application:
          maxAge: 1d
        audit:
          maxAge: 7d
        infra:
          maxAge: 7d
      type: elasticsearch
    managementState: Managed
    visualization:
      kibana:
        nodeSelector: 
          node-role.kubernetes.io/infra: ''
        tolerations:
        - effect: NoSchedule 
          key: node-role.kubernetes.io/infra 
          operator: Exists
          
        replicas: 1
      type: kibana
    
