apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp-s4bt4 
  name: ocp-s4bt4-infraocs-0
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp-s4bt4 
      machine.openshift.io/cluster-api-machineset: ocp-s4bt4-infraocs-0
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp-s4bt4 
        machine.openshift.io/cluster-api-machine-role: infra 
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: ocp-s4bt4-infraocs-0 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      taints:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        value: "true"

 
      providerSpec:
          value:
            apiVersion: ovirtproviderconfig.machine.openshift.io/v1beta1
            cluster_id: ecdd6108-81cb-11eb-a685-005056adf119
            cpu:
              cores: 16
              sockets: 1
              threads: 1
            credentialsSecret:
              name: ovirt-credentials
            id: ""
            kind: OvirtMachineProviderSpec
            memory_mb: 65536
            metadata:
              creationTimestamp: null
            name: ""
            os_disk:
              size_gb: 120
            template_name: ocp-s4bt4-rhcos
            type: server
            userDataSecret:
              name: worker-user-data
