apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: second
      endpoint: s3-openshift-storage.apps.ocphub.lab.seeweb
      insecure: true
      access_key: dAXjYeVmf1fhqQl48W1o
      secret_key: XXHJAIMhQeTmk+OTQG0KObUc7YoiTRVJ1jkUW0G0
