apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: master-machine-health-check
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machine-role: master
      #machine.openshift.io/cluster-api-machine-type: worker
      #machine.openshift.io/cluster-api-machineset: ocp-q7l2m-worker-0
  unhealthyConditions:
  - type:    "Ready"
    timeout: "300s" 
    status: "False"
  - type:    "Ready"
    timeout: "300s" 
    status: "Unknown"
  maxUnhealthy: "40%" 