apiVersion: batch/v1
kind: Job
metadata:
  name: bucket_creation_job
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 120 
  backoffLimit: 60   
  template:         
    metadata:
      name: bucket_creation_job
    spec:
      containers:
      - name: bucket_creation_job
        image: ubi8
        env:
        - ACCESS_KEY: {{ .Values.secret.accesskey }}
        - ACCESS_SECRET: {{ .Values.secret.secretkey }}
        - BUCKET_NAME: {{ .Values.bucketName }}
        command:
        - "curl -LO https://dl.min.io/client/mc/release/linux-amd64/mc"
        - "chmod +x ./mc"
        - "./mc alias set minio http://minio ${ACCESS_KEY} ${ACCESS_SECRET}"
        - "./mc mb minio/${BUCKET_NAME}"
      restartPolicy: OnFailure    