apiVersion: batch/v1
kind: Job
metadata:
  name: bucket-creation-job
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 120 
  backoffLimit: 60   
  template:         
    metadata:
      name: bucket-creation-job
    spec:
      containers:
      - name: bucket-creation-job
        image: ubi8
        env:
        - name: ACCESS_KEY
          value: {{ .Values.secret.accesskey }}
        - name: ACCESS_SECRET
          value: {{ .Values.secret.secretkey }}
        - name: BUCKET_NAME
          value: {{ .Values.bucketName }}
        command: ["/bin/sh","-c"]
        args:
        - cd /home;
          curl -LO https://dl.min.io/client/mc/release/linux-amd64/mc;
          chmod +x /home/mc;
          export AK=$(echo $ACCESS_KEY | base64 -d);
          export AS=$(echo $ACCESS_SECRET | base64 -d);
          ./mc  --config-dir=/home/ alias set minio http://minio $AK $AS;
          ./mc  --config-dir=/home/ mb minio/$BUCKET_NAME;
        volumeMounts:
        - name: tmp
          mountPath: /home

      restartPolicy: OnFailure
      volumes:
        - name: tmp
          emptyDir: {}    