apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Grafana.v1alpha1.integreatly.org,GrafanaDashboard.v1alpha1.integreatly.org,GrafanaDataSource.v1alpha1.integreatly.org
  generateName: custom-grafana-
  name: custom-grafana
  namespace: custom-grafana
spec:
  targetNamespaces:
  - custom-grafana
