apiVersion: autoscaling/v2beta2 
kind: HorizontalPodAutoscaler
metadata:
  name: memory-autoscale 
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: v1 
    kind: DeploymentConfig 
    name: quarkus-native2 
  minReplicas: 1 
  maxReplicas: 10 
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageUtilization: 50 