apiVersion: autoscaling/v2beta2 
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-resource-metrics-memory 
  namespace: test-hpa-memory
spec:
  scaleTargetRef:
    apiVersion: v1 
    kind: ReplicationController 
    name: quarkus-native2-1 
  minReplicas: 1 
  maxReplicas: 10 
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: AverageValue 
        averageValue: 500Mi 