apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocphub-vt8l4
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: infra
  name: ocphub-vt8l4-infra
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocphub-vt8l4
      machine.openshift.io/cluster-api-machineset: ocphub-vt8l4-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocphub-vt8l4
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: ocphub-vt8l4-infra
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          affinity_groups_names:
          - ocphub-vt8l4-compute
          apiVersion: ovirtproviderconfig.machine.openshift.io/v1beta1
          auto_pinning_policy: none
          cluster_id: ecdd6108-81cb-11eb-a685-005056adf119
          cpu:
            cores: 24
            sockets: 1
            threads: 1
          credentialsSecret:
            name: ovirt-credentials
          id: ""
          kind: OvirtMachineProviderSpec
          memory_mb: 94208
          metadata:
            creationTimestamp: null
          name: ""
          os_disk:
            size_gb: 120
          template_name: ocphub-vt8l4-rhcos
          type: server
          userDataSecret:
            name: worker-user-data
