---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: 'true'
    olm.providedAPIs: Tenant.v2.minio.min.io
  name: global-operators
  namespace: openshift-operators
spec: {}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/minio-operator.openshift-operators: ""
  name: minio-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: minio-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: minio-operator.v4.0.2




