apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configs
spec:
  destination:
    name: ''
    namespace: argo-test
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster
    repoURL: 'https://github.com/redhat-developer/openshift-gitops-getting-started'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true