apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: example
spec:
  provider:
    vault:
      server: "http://vault.lab.seeweb:8200"
      path: "bjpath"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "cloud-app"
          serviceAccountRef:
            name: "sample-external-secrets"
            
      
        