apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    app.kubernetes.io/instance: group-sync
    operators.coreos.com/group-sync-operator.group-sync-operator: ""
  name: group-sync-operator
  namespace: group-sync-operator
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: group-sync-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
 
